### GET USERS
GET http://localhost:3000/api/users

### CREATE USER
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "email": "lisamarie@hello.com",
    "password": "lisamarie12345"
}

### LOGIN USER
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "lisamarie.andersson@gmail.com",
    "password": "lisamarie123"
}

### LOGOUT USER
POST  http://localhost:3000/api/users/logout

### GET ORDERS
GET http://localhost:3000/api/orders/user

### GET ALL ORDERS
GET http://localhost:3000/api/orders/all

### GET ORDER BY ID
GET http://localhost:3000/api/orders/6475c6824a69464b86a75a2f

### CREATE ORDER
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "orderItems": [
    {
      "product": "6475be567e1d3b74c8d13ebd",
      "quantity": 2
    },
    {
      "product": "6475bdd37e1d3b74c8d13eae",
      "quantity": 1
    }
  ],
    "deliveryAddress": {
    "fullName": "Lisa Andersson",
    "email": "lisa.andersson@example.com",
    "phoneNumber": "1234567890",
    "address": "1234 Main St",
    "zipCode": "12345",
    "city": "Cityville"
  }
}

### UPDATE ORDER STATUS
PUT http://localhost:3000/api/orders/status/6475c6824a69464b86a75a2f
Content-Type: application/json

{
    "status": "shipped"
}



