### GET 
GET http://localhost:3000/api/products
Content-Type:  application/json

### Post

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "_id": "abc123",
  "title": "Testprodukt",
  "description": "Info about product",
  "categories": "Testkategori",
  "price": "50",
  "quantity": "30",
  "stock": "20",
  "imageId": "12",
  "imageURL": "www.test.se"
}

### Delete

DELETE http://localhost:3000/api/products/abc123
Content-Type: application/json

{
  "_id": "abc123",
  "title": "Testprodukt",
  "description": "Info about product",
  "categories": "Testkategori",
  "price": "50",
  "quantity": "30",
  "stock": "20",
  "imageId": "12",
  "imageURL": "www.test.se"
}
