### GET 
GET http://localhost:3000/api/products
Content-Type:  application/json

### GET 
GET http://localhost:3000/api/products/cde321
Content-Type:  application/json

### Post

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "_id": "cde321",
  "title": "Testprodukt",
  "description": "Info about product",
  "summary": ["1 sak", "2 sak", "3 sak"],
  "categories": "Testkategori",
  "price": "50",
  "quantity": "30",
  "stock": "20",
  "imageId": "12",
  "imageURL": "www.test.se",
  "secondImageId": "25",
  "secondImageURL": "www.test2.se",
  "rating": "4.5",
  "usersRated": "7"
}

### Delete

DELETE http://localhost:3000/api/products/cde321
Content-Type: application/json

{
   "_id": "cde321",
  "title": "Testprodukt",
  "description": "Info about product",
  "summary": ["1 sak", "2 sak", "3 sak"],
  "categories": "Testkategori",
  "price": "50",
  "quantity": "30",
  "stock": "20",
  "imageId": "12",
  "imageURL": "www.test.se",
  "secondImageId": "25",
  "secondImageURL": "www.test2.se",
  "rating": "4.5",
  "usersRated": "7"
}

### PUT 
PUT http://localhost:3000/api/products/cde321
Content-Type: application/json

{
  "title": "Testprodukten",
  "description": "Info about product okej kul",
  "summary": ["1 sak", "2 sak", "3 sak"],
  "categories": "Testkategori",
  "price": "900",
  "quantity": "30",
  "stock": "20",
  "imageId": "12",
  "imageURL": "www.testet.se",
  "secondImageId": "25",
  "secondImageURL": "www.test2.se",
  "rating": "2",
  "usersRated": "7"
}